/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "njijaaivkccpsxlfjcja"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qaWphYWl2a2NjcHN4bGZqY2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyODkwODAsImV4cCI6MjA4Nzg2NTA4MH0.6PsY-Hm1CwMfFPX_REe4bAFq6o3FvRuz52zVBHl-uX8"